/**
 * Konfigurator-aspnetcore-Backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AddGameMapRequestDto } from '../model/addGameMapRequestDto';
import { AddGameMapResponseDtoServiceResponseDto } from '../model/addGameMapResponseDtoServiceResponseDto';
import { AddSingleGraphicRequestDto } from '../model/addSingleGraphicRequestDto';
import { GetConfigurationDataResponseDtoServiceResponseDto } from '../model/getConfigurationDataResponseDtoServiceResponseDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { backendPath } from './api';


@Injectable()
export class ConfigurationService {

    protected basePath = backendPath;
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public configurationAddGamePost(body?: AddGameMapRequestDto, observe?: 'body', reportProgress?: boolean): Observable<AddGameMapResponseDtoServiceResponseDto>;
    public configurationAddGamePost(body?: AddGameMapRequestDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AddGameMapResponseDtoServiceResponseDto>>;
    public configurationAddGamePost(body?: AddGameMapRequestDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AddGameMapResponseDtoServiceResponseDto>>;
    public configurationAddGamePost(body?: AddGameMapRequestDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<AddGameMapResponseDtoServiceResponseDto>('post',`${this.basePath}/Configuration/addGame`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public configurationAddSingleGraphicPost(body?: AddSingleGraphicRequestDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public configurationAddSingleGraphicPost(body?: AddSingleGraphicRequestDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public configurationAddSingleGraphicPost(body?: AddSingleGraphicRequestDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public configurationAddSingleGraphicPost(body?: AddSingleGraphicRequestDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/Configuration/addSingleGraphic`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public configurationGetDataGet(observe?: 'body', reportProgress?: boolean): Observable<GetConfigurationDataResponseDtoServiceResponseDto>;
    public configurationGetDataGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetConfigurationDataResponseDtoServiceResponseDto>>;
    public configurationGetDataGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetConfigurationDataResponseDtoServiceResponseDto>>;
    public configurationGetDataGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GetConfigurationDataResponseDtoServiceResponseDto>('get',`${this.basePath}/Configuration/getData`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
