/**
 * Konfigurator-aspnetcore-Backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DesignDto } from './designDto';

export interface GetConfigurationDataResponseDto { 
    barrierDesignDtos?: Array<DesignDto>;
    characterDesignDtos?: Array<DesignDto>;
    targetDesignDtos?: Array<DesignDto>;
    tileDesignDtos?: Array<DesignDto>;
}